- name: Playbook for running tasks on web servers from inventory file from group
  hosts: ec2webservers
  become: true # For whole tasks with sudo privilege
  tasks:
    - name: Copy first file with permissions
      ansible.builtin.copy:
        src: ./app/calculator.py
        dest: /home/ubuntu/calculator.py
        mode: '0777'

    - name: Copy second file with permissions
      ansible.builtin.copy:
        src: ./app/main.py
        dest: /home/ubuntu/main.py
        mode: '0777'

    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install Python and pip
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - python3
        - python3-pip

    - name: Install requests library
      ansible.builtin.pip:
        name: "requests>=2.25.1"
        state: present
        executable: pip3

    - name: Run a script using an executable in a system path
      ansible.builtin.command:
        cmd: python3 /home/ubuntu/main.py