[tool.poetry]
name = "my-python-app"
version = "0.1.0"
description = "App with logging"
authors = ["vbazh"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9.6"
logging = "^0.4.9.6"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
