name: Create Release

on:
  push:
    tags:
      - 'v*.*.*'  # Triggers the workflow for any tag that follows the format vX.X.X

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up GitHub CLI
        uses: actions/setup-gh@v1  # Sets up the GitHub CLI
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release
        run: gh release create ${{ github.ref_name }} --generate-notes  # Create release
