name: Check README file

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run README check script
        run: chmod +x ./01_git/task1_badge/src/check_readmemd.sh && ./01_git/task1_badge/src/check_readmemd.sh
      - name: Commit changes
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git diff --exit-code --quiet README.md || {
          echo "There are changes in README.md. Committing..."
          git add README.md 
          git commit -m 'Update status badge in README' 
          git push
          }
      - name: Install python and jinja
        run: echo "Installation in progress..."