name: Check README file

on: [push]

jobs:
  check-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run README check script
        run: chmod +x ./task_1/src/task1_check_readmefile.sh && ./task_1/src/task1_check_readmefile.sh