name: Test and Build

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          export PATH="$HOME/.local/bin:$PATH"

      - name: Install dependencies
        run: poetry install --with test

      - name: Run tests with coverage
        run: |
          poetry run coverage run -m pytest
          poetry run coverage report

      - name: Check coverage
        run: |
          poetry run coverage report | tail -n 1 | awk '{print $4}' | grep -q '^6[0-9]' || exit 1

  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          export PATH="$HOME/.local/bin:$PATH"

      - name: Install production dependencies
        run: poetry install --no-dev

      - name: Build the Docker image
        run: |
          docker build -t task3-project .
